name: CD App (BuildImage and Push)

on:
  workflow_run:
    workflows: ["CI Node App"]
    types:
      - completed

jobs:
  Build_Docker_Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate unique tag
      run: echo "UNIQUE_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
          cd Pass-List-App
          docker build . --file dockerFile_2 --tag students.azurecr.io/axity-app:$UNIQUE_TAG
    - name: Check 4 Image
      run: docker images
      
    - name: Push Image to ACR
      run: |
            docker login -u token-access -p ${{ secrets.ACR_TOKEN_VALUE }} students.azurecr.io
            docker push students.azurecr.io/axity-app:$UNIQUE_TAG
     
