# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  build:

    runs-on: JZEPEDA-8LFW2X2

    steps:
    - uses: actions/checkout@v4
    - name: configuracion variable de entorno
      run:  echo "APP_DIR=Playground_Actions" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.APP_DIR }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.APP_DIR }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.APP_DIR }}
