# Nombre del workflow. Este es el nombre que verás en la pestaña de Actions en GitHub.
name: Hello World Workflow

# 'on' define los eventos que desencadenan la ejecución del workflow.
# En este caso, el workflow se ejecutará solo cuando se active manualmente.
on: 
  workflow_dispatch:  # Este evento permite ejecutar el workflow de forma manual.

# 'jobs' define los trabajos que se ejecutarán como parte de este workflow.
jobs:
  say-hello:  # Nombre del job.
  
    # 'runs-on' define el tipo de runner (máquina) que ejecutará este job.
    # Aquí usamos 'ubuntu-latest', que es una máquina virtual con Ubuntu.
    runs-on: ubuntu-latest
    
    # 'steps' define los pasos que se ejecutarán dentro de este job.
    steps:
    
      # Primer paso: Checkout del código del repositorio.
      # Esta acción obtiene el código fuente del repositorio para que esté disponible en la máquina.
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Segundo paso: Imprimir "Hello, World!" en la consola.
      # Aquí simplemente ejecutamos un comando de shell que imprime "Hello, World!".
      - name: Run Hello World Script
        run: echo "Hello, World!"

      - name: Print repo name
        run: ls

      - name: Print GitHub variable
        run: |
          # Buscar todos los archivos .tf en el repositorio
          find . -name "*.tf" > tf_files.txt
          
          # Mostrar la lista de archivos encontrados
          echo "Archivos .tf encontrados:"
          cat tf_files.txt
          
          # Contar los recursos diferentes de Terraform
          resource_count=$(grep -oh -E 'resource "(.*?)"' $(cat tf_files.txt) | sort | uniq -c)
          
          echo "Conteo de recursos de Terraform:"
          echo "$resource_count"
          
          # Contar el número total de tipos de recursos diferentes
          unique_resource_types=$(grep -oh -E 'resource "(.*?)"' $(cat tf_files.txt) | sort | uniq | wc -l)
          
          echo "Número total de tipos de recursos diferentes: $unique_resource_types"
